# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{relevance}
  s.version = "0.1.0"

  s.required_rubygems_version = nil if s.respond_to? :required_rubygems_version=
  s.authors = ["Justin Camerer", "Ed Howland"]
  s.bindir = nil
  s.cert_chain = nil
  s.date = %q{2010-07-14}
  s.description = %q{formsanity relevance gem}
  s.email = %q{ed.howland@gmail.com}
  s.files = [
    "Rakefile",
     "VERSION",
     "lib/relevance.rb",
     "lib/relevance_grammar.rb",
     "lib/relevance_grammar.treetop",
     "lib/relevance_interpreter.rb",
     "spec/relevance_grammar_spec.rb",
     "spec/relevance_spec.rb"
  ]
  s.homepage = %q{http://github.com/edhowland/relevance}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = nil
  s.required_ruby_version = nil
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{formsanity relevance}
  s.test_files = [
    "spec/relevance_grammar_spec.rb",
     "spec/relevance_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

